name: btcmining
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  flutter_iconly: ^1.0.2
  fancy_shimmer_image: ^2.0.3
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  uuid: ^4.0.0
  readmore: ^2.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.14
  firebase_dynamic_links: ^5.3.6
  flutter_text_form_field: ^1.0.3
  share_plus: ^4.5.3
  image_picker: ^1.0.4




  ## -- Home Page Upper Swiper
  card_swiper: ^3.0.1

## -- STATE MANAGEMENT
  get: ^4.6.5

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.7
  firebase_database: ^10.2.6
  firebase_storage: ^11.2.7
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  app_settings: ^5.1.1

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.2.16


  http: ^0.13.5
  chart_sparkline: ^1.0.13
  syncfusion_flutter_charts: ^20.4.48


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
#flutter_launcher_icons:
#    android: true
#    ios: true
#    image_path: "assets/icon/icon.png"




flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/image/user.png
    - assets/offers/
    - assets/coin/
    - assets/splash/
    - assets/background/
    - assets/partners/
    - assets/offers/logSplash.png
    - assets/icon/logooo.png


  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
