// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVNQvwINGoH_VDjQmIKatYNDH-mdLPKmQ',
    appId: '1:961887182019:web:f8627cdcbc98154cf61676',
    messagingSenderId: '961887182019',
    projectId: 'btcmining-bf56f',
    authDomain: 'btcmining-bf56f.firebaseapp.com',
    storageBucket: 'btcmining-bf56f.appspot.com',
    measurementId: 'G-D7J52KM3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Bzz7mwPTQnVIciu_cde5qW77pmeNv50',
    appId: '1:961887182019:android:e47e795b78d2ebe1f61676',
    messagingSenderId: '961887182019',
    projectId: 'btcmining-bf56f',
    storageBucket: 'btcmining-bf56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJmIjt1TUAZqlfDQ6aIzP0VPpzl6SJ3nI',
    appId: '1:961887182019:ios:3ad9244b81350aa2f61676',
    messagingSenderId: '961887182019',
    projectId: 'btcmining-bf56f',
    storageBucket: 'btcmining-bf56f.appspot.com',
    androidClientId: '961887182019-j7vbiiskv73onifaf23k46arvl13vfug.apps.googleusercontent.com',
    iosClientId: '961887182019-fop3te094qjb9tj8r52fogcjrem9ldin.apps.googleusercontent.com',
    iosBundleId: 'com.example.btcmining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJmIjt1TUAZqlfDQ6aIzP0VPpzl6SJ3nI',
    appId: '1:961887182019:ios:3ad9244b81350aa2f61676',
    messagingSenderId: '961887182019',
    projectId: 'btcmining-bf56f',
    storageBucket: 'btcmining-bf56f.appspot.com',
    androidClientId: '961887182019-j7vbiiskv73onifaf23k46arvl13vfug.apps.googleusercontent.com',
    iosClientId: '961887182019-fop3te094qjb9tj8r52fogcjrem9ldin.apps.googleusercontent.com',
    iosBundleId: 'com.example.btcmining',
  );
}
